package medresourcemanagement;

public enum Specialism {
    CARDIOLOGY, PULMONOLOGY, INFECTIOUS_DISEASE,HEMATOLOGY, INTENSIVE_CARE_MEDICINE,
    NEUROLOGY, OPHTHALMOLOGY,ORTHOPEDICS,UROLOGY,SURGERY
}
